version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jer-yung-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    restart: unless-stopped
